services:
  - type: web
    name: isolate-vocals
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /api/health
    numInstances: 1
    envVars:
      - key: PORT
        value: 10000
